// ExportPseudocode.java — Ghidra headless post-script
// Decompiles all functions in the current program and writes pseudocode to a .c file.
// Also writes a function_index.tsv with: name<TAB>address<TAB>size for each function.
//
// Usage (via analyzeHeadless -process mode):
//   analyzeHeadless <projectDir> <projectName> \
//     -process <programName> \
//     -postScript ExportPseudocode.java <outputDir>
//
// Args (via getScriptArgs()):
//   args[0] — output directory (absolute path); pseudocode written to <outputDir>/<programName>.c
//             and index written to <outputDir>/<programName>.tsv
//
// Output format for <programName>.c:
//   // === FUNCTION: <name> @ <addr> (size=<N> bytes) ===
//   <decompiled C code>
//   // === END: <name> ===
//
// Output format for <programName>.tsv:
//   <name>\t<address_hex>\t<size_decimal>
//   (one row per function, no header)

import ghidra.app.script.GhidraScript;
import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileOptions;
import ghidra.app.decompiler.DecompileResults;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.FunctionIterator;
import ghidra.program.model.listing.Program;
import ghidra.program.model.address.Address;
import ghidra.util.task.TaskMonitor;

import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;

public class ExportPseudocode extends GhidraScript {

    @Override
    public void run() throws Exception {
        String[] args = getScriptArgs();
        if (args.length < 1) {
            println("ERROR: Usage: ExportPseudocode.java <outputDir>");
            return;
        }

        String outputDir = args[0];
        File dir = new File(outputDir);
        if (!dir.exists()) {
            dir.mkdirs();
        }

        Program prog = currentProgram;
        String progName = prog.getName();
        // Strip any file extension (e.g. ".bin")
        int dotIdx = progName.lastIndexOf('.');
        String baseName = (dotIdx > 0) ? progName.substring(0, dotIdx) : progName;

        File pseudocodeFile = new File(dir, baseName + ".c");
        File indexFile = new File(dir, baseName + ".tsv");

        println("ExportPseudocode: program=" + progName + " -> " + pseudocodeFile.getAbsolutePath());

        // Set up decompiler
        DecompInterface decomp = new DecompInterface();
        DecompileOptions options = new DecompileOptions();
        decomp.setOptions(options);
        decomp.setSimplificationStyle("decompile");

        boolean opened = decomp.openProgram(prog);
        if (!opened) {
            println("ERROR: DecompInterface failed to open program: " + progName);
            // Still write files (empty pseudocode) so downstream scripts can detect failure
        }

        FunctionIterator funcs = prog.getListing().getFunctions(true);
        int total = 0;
        int failed = 0;

        try (PrintWriter cOut = new PrintWriter(new FileWriter(pseudocodeFile));
             PrintWriter tsvOut = new PrintWriter(new FileWriter(indexFile))) {

            cOut.println("// Pseudocode export: " + progName);
            cOut.println("// Generated by ExportPseudocode.java (Ghidra headless post-script)");
            cOut.println("// Processor: " + prog.getLanguage().getLanguageID());
            cOut.println("// Compiler: " + prog.getCompilerSpec().getCompilerSpecID());
            cOut.println("");

            while (funcs.hasNext() && !monitor.isCancelled()) {
                Function fn = funcs.next();
                String fnName = fn.getName();
                Address entry = fn.getEntryPoint();
                long bodySize = fn.getBody().getNumAddresses();

                // Write TSV row
                tsvOut.println(fnName + "\t" + entry.toString() + "\t" + bodySize);

                // Write C section header
                cOut.println("// === FUNCTION: " + fnName + " @ " + entry + " (size=" + bodySize + " bytes) ===");

                if (opened) {
                    try {
                        DecompileResults results = decomp.decompileFunction(fn, 30, monitor);
                        if (results != null && results.decompileCompleted()) {
                            String code = results.getDecompiledFunction().getC();
                            cOut.print(code);
                        } else {
                            String errMsg = (results != null) ? results.getErrorMessage() : "null results";
                            cOut.println("/* DECOMPILE FAILED: " + errMsg + " */");
                            failed++;
                        }
                    } catch (Exception e) {
                        cOut.println("/* DECOMPILE EXCEPTION: " + e.getMessage() + " */");
                        failed++;
                    }
                } else {
                    cOut.println("/* DECOMPILER NOT AVAILABLE */");
                    failed++;
                }

                cOut.println("// === END: " + fnName + " ===");
                cOut.println("");
                total++;
            }

            cOut.println("// Total functions: " + total + " (decompile failures: " + failed + ")");
        }

        decomp.dispose();
        println("ExportPseudocode: wrote " + total + " functions (" + failed + " failures) to " + pseudocodeFile);
        println("ExportPseudocode: index written to " + indexFile);
    }
}
