import Foundation

enum OriginalWagonContinuation {
    /// CODE16:17b6–1912, called by the Continue command at0ce0. Replacements
    /// are installed even if another missing part prevents departure. No day,
    /// random draw, or repair event is generated by this gate.
    static func prepare(_ trip: inout Journey) -> Supply? {
        if trip.inventory[.oxen] == 0 { return .oxen }
        var missing: Supply?
        for part in trip.damagedParts {
            if trip.inventory[part] == 0 { missing = part }
            else {
                trip.inventory[part] -= 1
                trip.clearBroken(part)
            }
        }
        return missing
    }

    static func message(for missing: Supply) -> String {
        let reason: String
        switch missing {
        case .oxen: reason = "need some oxen"
        case .wheels: reason = "need a wagon wheel"
        case .axles: reason = "need a wagon axle"
        case .tongues: reason = "need a wagon tongue"
        default: preconditionFailure("Not an original wagon movement blocker")
        }
        return "You can’t continue because you \(reason)."
    }
}
